test: FAPI fix load_pem_public_key() missing 'backend'
        # verify via openssl
>       public_key = serialization.load_pem_public_key(key_public_pem)
E       TypeError: load_pem_public_key() missing 1 required positional argument: 'backend'

Signed-off-by: William Roberts <william.c.roberts@intel.com>