setup: fixup compilation with fortify source enabled
This triggered on NixOS builds because the default gcc is configured
with fortify source, which in turns causes issues with pycparser:
<details>
```
Traceback (most recent call last):
  File "/build/tpm2-pytss-2.1.0/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 280, in <module>
    setup(
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/nix/store/d6ypnlsrcgc66zzgjbwx543zylxqyn0b-python3.10-wheel-0.38.4/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
    self.run_command("build")
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/nix/store/b7rq6rjxyg23rwx0s8bv6vi7k6kwm3py-python3.10-setuptools-67.4.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/nix/store/8wimrjbr34hlbya0fs7ghrbz5sdmwzbf-python3.10-cffi-1.15.1/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 144, in run
    base_class.run(self)
  File "setup.py", line 230, in run
    type_map, element_type_map = self.get_mappings()
  File "setup.py", line 210, in get_mappings
    past = parser.parse(pdata, "tss2_policy.h")
  File "/nix/store/s5r2qahfz2x967ggif24j4bk72gb0g4x-python3.10-pycparser-2.21/lib/python3.10/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/nix/store/s5r2qahfz2x967ggif24j4bk72gb0g4x-python3.10-pycparser-2.21/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking,
tokenfunc)
  File "/nix/store/s5r2qahfz2x967ggif24j4bk72gb0g4x-python3.10-pycparser-2.21/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/nix/store/s5r2qahfz2x967ggif24j4bk72gb0g4x-python3.10-pycparser-2.21/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/nix/store/s5r2qahfz2x967ggif24j4bk72gb0g4x-python3.10-pycparser-2.21/lib/python3.10/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/nix/store/s5r2qahfz2x967ggif24j4bk72gb0g4x-python3.10-pycparser-2.21/lib/python3.10/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /nix/store/0ccvlygpc7p5zyfsyz8mmg9ycqkvrcp2-glibc-2.37-8-dev/include/bits/poll2.h:26:78: before: __asm__
```
</details>

This patch disables the fortify source for the pre-processor phase.

Signed-off-by: Arthur Gautier <baloo@superbaloo.net>