test: FAPI fix __init__() missing argument 'backend'
Fix error:
    def sha256(data: bytes) -> bytes:
        """Calculate the SHA256 digest of given data."""
>       digest = hashes.Hash(hashes.SHA256())
E       TypeError: __init__() missing 1 required positional argument: 'backend'

test/test_fapi.py:48: TypeError

Signed-off-by: William Roberts <william.c.roberts@intel.com>