test: skip test when camellia not supported
When the simulator doesn't support camellia, this exception is thrown
and the test fails:

FAILED test/test_utils.py::TestUtils::test_make_credential_ecc_camellia - tpm2_pytss.TSS2_Exception.TSS2_Exception: tpm:parameter(2):unsupporte...

Fix it by skipping the test and also add a helper that when setting up
the test framework also caches the supported algoirthms and has a helper
for skipping tests when the TPM simulator lacks support.

Signed-off-by: William Roberts <william.c.roberts@intel.com>