types: calls to cryptography < 3.1 require backend
Fixes:
test/test_esapi.py:948:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tpm2_pytss/types.py:1635: in getName
    return self.nvPublic.getName()
tpm2_pytss/types.py:1887: in getName
    name = getname(self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

obj = <tpm2_pytss.types.TPMS_NV_PUBLIC object at 0x7f09d2e36430>

    def getname(obj):
        dt = _get_digest(obj.nameAlg)
        if dt is None:
            raise ValueError(f"unsupported digest algorithm: {d}")
>       d = hashes.Hash(dt())
E       TypeError: __init__() missing 1 required positional argument: 'backend'

tpm2_pytss/crypto.py:130: TypeError

Signed-off-by: William Roberts <william.c.roberts@intel.com>