test: skip TraditionalOpenSSL PEM assertions in FIPS mode
When running in FIPS mode python-cryptography refuses to produce
password-encrypted TraditionalOpenSSL (PKCS#1) PEM output:

  ValueError: Encrypted traditional OpenSSL format is not supported in FIPS mode

Legacy PEM password encryption uses non-FIPS-approved KDFs not
permitted in FIPS mode.
Follow exising pattern of probing the optional crypto capability and
calling self.skipTest() when the backend does not provide it.

Signed-off-by: Stewart Smith <trawets@amazon.com>