test: FAPI fix __init__() missing argument: 'backend'
Fixes:
    def test_sign(self, sign_key):
        # create signature
        message = b"Hello World"
>       digest = hashes.Hash(hashes.SHA256())
E       TypeError: __init__() missing 1 required positional argument: 'backend'

test/test_fapi.py:253: TypeError

Signed-off-by: William Roberts <william.c.roberts@intel.com>