test: fix FAPI generate_private_key() missing argument: 'backend'
Fixes:
    @pytest.fixture
    def cryptography_key(self):
>       key = ec.generate_private_key(ec.SECP256R1())
E       TypeError: generate_private_key() missing 1 required positional argument: 'backend'

test/test_fapi.py:71: TypeError

Signed-off-by: William Roberts <william.c.roberts@intel.com>