crypto: calls to cryptography < 3.1 require backend arg
Fixes errors:

    def public_from_pem(data, obj):
>       key = load_pem_public_key(data)
E       TypeError: load_pem_public_key() missing 1 required positional argument: 'backend'

tpm2_pytss/crypto.py:48: TypeError

backend set to None default didn't appear until cryptography >= 3.1.
See commit:
  - https://github.com/pyca/cryptography/commit/24070d795443f9b01c926a9f7111e4405c0dbaa6

Signed-off-by: William Roberts <william.c.roberts@intel.com>