crypto: fix missing backend argument
Fixes errors like:
    def private_key_from_encoding(data):
        sdata = data.strip()
        key = None
        if sdata.startswith(b"-----BEGIN RSA PRIVATE KEY-----") or sdata.startswith(
            b"-----BEGIN EC PRIVATE KEY-----"
        ):
            key = load_pem_private_key(sdata, password=None)
        else:
            try:
>               key = load_der_private_key(data, password=None)
E               TypeError: load_der_private_key() missing 1 required positional argument: 'backend'

Signed-off-by: William Roberts <william.c.roberts@intel.com>